### ISSUE TITLE
ta-common crate causes build to fail

### ISSUE THREAD

**Issue by Shariffintech** [Big-Bytes-Labs/fisher-rs#1]
When I try to run the initial setup I get the following error locally:

![Screenshot 2023-09-30 at 3 31 37 AM](https://github.com/Big-Bytes-Labs/fisher-rs/assets/22308837/f19ed847-6b4c-419e-a276-2a136dba5d1b)

I cant seem to find a sufficient workaround for installing / running this..

**Comment by Vilayat-Ali** [comment]
Well... it shouldn't be. I'm using Ubuntu and it is working flawlessly. I will suggesting removing anyhow dependency and then running it, as we are re-writing the implementation to make it more python-based pandas agnostic.

**Comment by Vilayat-Ali** [comment]
That shouldnt be the case in upcoming releases. I'm marking this issue as resolved.
